image: gitlab.zengenti.com:4567/ops/zengenti-dind:latest

include:
  - 'https://gitlab.zengenti.com/ops/contensis-ci/-/raw/main/push-block.yml'
  - 'https://gitlab.zengenti.com/ops/contensis-ci/-/raw/main/release-block.yml'

stages:
  - latest-build
  - live-build
  - push-block
  - release-block
#  - storybook-latest-build // Temporarily disable the Docker stage until a resolution is reached regarding integrating storybook with Blocks

variables:
  DOCKER_DRIVER: overlay2
  STORYBOOK: ''
  APP_BUILDER_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/app-builder'
  APP_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/app'
  STORYBOOK_BUILDER_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/storybook-builder'
  STORYBOOK_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/storybook'
  MASTER_APP: '$CI_REGISTRY_IMAGE/master/app'
  DEVELOP_APP: '$CI_REGISTRY_IMAGE/develop/app'

services:
  - docker:dind

build-latest-code:
  stage: latest-build
  except:
    - tags
  script:
    - docker pull $APP_BUILDER_IMAGE:latest || true
    - echo "{\"commitRef\":\"$CI_COMMIT_SHA\",\"pipelineIID\":\"$CI_PIPELINE_IID\",\"pipelineUrl\":\"$CI_PIPELINE_URL\",\"buildNo\":\"$CI_PIPELINE_ID\",\"branchName\":\"$CI_COMMIT_REF_NAME\",\"registryImage\":\"$CI_REGISTRY_IMAGE\"}" > version.json
    - docker build --force-rm --cache-from $APP_BUILDER_IMAGE:latest -t $APP_BUILDER_IMAGE:latest -f docker/nodebuilder.DockerFile .
    - docker push $APP_BUILDER_IMAGE:latest
    - docker pull $APP_IMAGE:latest || true
    - docker build --force-rm --cache-from $APP_IMAGE:latest -t $APP_IMAGE:latest --build-arg builder_image=$APP_BUILDER_IMAGE:latest -f docker/ci-build.DockerFile .
    - docker push $APP_IMAGE:latest
    - docker tag "$APP_IMAGE:latest" "$APP_IMAGE:build-$CI_PIPELINE_IID"
    - docker push "$APP_IMAGE:build-$CI_PIPELINE_IID"

#build-storybook:
# stage: storybook-latest-build
# except:
#   - tags
# script:
#   - docker pull $STORYBOOK_BUILDER_IMAGE:latest || true
#   - docker build --compress --force-rm --cache-from $STORYBOOK_BUILDER_IMAGE:latest -t $STORYBOOK_BUILDER_IMAGE:latest -f docker/storybook-builder.DockerFile .
#   - docker push $STORYBOOK_BUILDER_IMAGE:latest
#   - docker build --compress --force-rm -t $STORYBOOK_IMAGE:latest --build-arg builder_image=$STORYBOOK_BUILDER_IMAGE:latest -f  docker/storybook-http.DockerFile .
#   - docker push $STORYBOOK_IMAGE:latest
# environment:
#   name: storybook
#   url: http://storybook.latest.$CI_PROJECT_NAME.contensis.cloud

build-live-code-for-production:
  stage: live-build
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^release-.*$/
  except:
    - branches
  script:
    - docker pull "$MASTER_APP:latest"
    - docker tag "$MASTER_APP:latest" "$MASTER_APP:release"
    - docker push "$MASTER_APP:release"
    - docker tag "$MASTER_APP:latest" "$MASTER_APP:$CI_COMMIT_TAG"
    - docker push "$MASTER_APP:$CI_COMMIT_TAG"

push-to-contensis:
  stage: push-block
  variables:
    alias: leif
    project_id: website
    block_id: react-starter
    image_uri: $APP_IMAGE:build-$CI_PIPELINE_IID
    release: 'false' # Whether to release the block upon successful push
    tag_repo: 'true' # Whether to push a tag to the git repo upon successful block push (git_token is required if this is 'true'). Defaults to false.
    # First create a Project Access Token e.g Tag block version (access: api, read_repository) and copy it
    # Then create a CI/CD Variable called GITLAB_ACCESS_TOKEN and paste the token
    git_token: $GITLAB_ACCESS_TOKEN

# Releasing the block (with a `release-*` tag)
release-contensis-block:
  stage: release-block
  variables:
    alias: leif
    project_id: website
    block_id: react-starter
