const ACTION_PREFIX = '@CONFIG/';
export const GET_SITE_CONFIG = `${ACTION_PREFIX}GET_SITE_CONFIG`;
export const SET_SITE_CONFIG = `${ACTION_PREFIX}SET_SITE_CONFIG`;
export const GET_SITE_CONFIG_ERROR = `${ACTION_PREFIX}GET_SITE_CONFIG_ERROR`;
